// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7se1g2jvSLjltTYrhq-3fZulYsRlom0M',
    appId: '1:913341406190:web:e246b003e8f75fb42bccff',
    messagingSenderId: '913341406190',
    projectId: 'scrabbly',
    authDomain: 'scrabbly.firebaseapp.com',
    storageBucket: 'scrabbly.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9-YIsH6eFYYHCrMm6xblitHdmWWUDW6Y',
    appId: '1:913341406190:android:faa9e00dc8d7f4bc2bccff',
    messagingSenderId: '913341406190',
    projectId: 'scrabbly',
    storageBucket: 'scrabbly.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx4Y8K6z19sXSemf5t2w2_szkB8YrdRgU',
    appId: '1:913341406190:ios:294b7c0dbd72e3282bccff',
    messagingSenderId: '913341406190',
    projectId: 'scrabbly',
    storageBucket: 'scrabbly.appspot.com',
    iosClientId: '913341406190-aaf9jhsbbf4ckg8acjjouivsgg23hosj.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrabbly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx4Y8K6z19sXSemf5t2w2_szkB8YrdRgU',
    appId: '1:913341406190:ios:7e2671900942b1da2bccff',
    messagingSenderId: '913341406190',
    projectId: 'scrabbly',
    storageBucket: 'scrabbly.appspot.com',
    iosClientId: '913341406190-3imhed2j0kljpekb9b2ljlnje9rokj78.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrabbly.RunnerTests',
  );
}
